default: &default
  adapter: postgresql
  encoding: unicode
  username: todoanhienvinh
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Merge-checklist_development

test:
  <<: *default
  database: Merge-checklist_test

production:
  <<: *default
  database: Merge-checklist_production
  username: todoanhienvinh
  password:
